global using System;
global using System.Collections.Generic;
global using System.Globalization;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using Not.Localization;
global using Not.Domain;
global using EMS.Domain.Objects;