// ReSharper disable InconsistentNaming
namespace EnduranceJudge.Localization.Strings;

public class Words
{
    public static string SAVE                              { get; internal set; }
    public static string UPDATE                            { get; internal set; }
    public static string REMOVE                            { get; internal set; }
    public static string SEARCH                            { get; internal set; }
    public static string CLEAR                             { get; internal set; }
    public static string CREATE                            { get; internal set; }
    public static string BACK                              { get; internal set; }
    public static string YES                               { get; internal set; }
    public static string NO                                { get; internal set; }
    public static string RECOVERY_IN_MINUTES_TEXT          { get; internal set; }
    public static string LENGTH_IN_KM_TEXT                 { get; internal set; }
    public static string FINAL                             { get; internal set; }
    public static string UPDATE_COMPETITION                { get; internal set; }
    public static string UPDATE_PHASE_TEXT                 { get; internal set; }
    public static string SELECT_WORK_DIRECTORY             { get; internal set; }
    public static string SELECT_IMPORT_FILE                { get; internal set; }
    public static string NAME                              { get; internal set; }
    public static string START_TIME                        { get; internal set; }
    public static string POPULATED_PLACE                   { get; internal set; }
    public static string TYPE                              { get; internal set; }
    public static string ROLE                              { get; internal set; }
    public static string ORDER                             { get; internal set; }
    public static string IS_FINAL                          { get; internal set; }
    public static string RFID_NUMBER                       { get; internal set; }
    public static string MAX_AVERAGE_SPEED_IN_KMH          { get; internal set; }
    public static string HAS_AVERAGE_SPEED_LIMIT           { get; internal set; }
    public static string MAX_RECOVERY_TIME_IN_MINS         { get; internal set; }
    public static string REST_TIME_IN_MINS                 { get; internal set; }
    public static string FEI_ID                            { get; internal set; }
    public static string FIRST_NAME                        { get; internal set; }
    public static string LAST_NAME                         { get; internal set; }
    public static string BREED                             { get; internal set; }
    public static string TRAINER_FEI_ID                    { get; internal set; }
    public static string TRAINER_FIRST_NAME                { get; internal set; }
    public static string TRAINER_LAST_NAME                 { get; internal set; }
    public static string IS_STALLION                       { get; internal set; }
    public static string CLUB                              { get; internal set; }
    public static string MANAGER                           { get; internal set; }
    public static string NUMBER                            { get; internal set; }
    public static string START                             { get; internal set; }
    public static string KM                                { get; internal set; }
    public static string LENGTH_IN_KM                      { get; internal set; }
    public static string HOURS_SYMBOL                      { get; internal set; }
    public static string KM_PER_HOUR                       { get; internal set; }
    public static string KIDS                              { get; internal set; }
    public static string ADULTS                            { get; internal set; }
    public static string CATEGORY                          { get; internal set; }
    public static string COMPLETE_UNSUCCESSFULLY           { get; internal set; }
    public static string UPDATE_PERSONNEL                  { get; internal set; }
    public static string _YES                              { get; internal set; }
    public static string _NO                               { get; internal set; }
    public static string EXPAND                            { get; internal set; }
    public static string COLLAPSE                          { get; internal set; }
    public static string REQUIRE_COMPULSORY_INSPECTION     { get; internal set; }
    public static string _RE_INSPECTION                    { get; internal set; }
    public static string _NUMBER                           { get; internal set; }
    public static string PRINT                             { get; internal set; }
    public static string EDIT                              { get; internal set; }
    public static string VIEW                              { get; internal set; }
    public static string ADD                               { get; internal set; }
    public static string ADD_PARTICIPANTS_TO               { get; internal set; }
    public static string APPLICATION_ERROR                 { get; internal set; }
    public static string VALIDATION_MESSAGE                { get; internal set; }
    public static string CONFIRMATION                      { get; internal set; }
    public static string MARE                              { get; internal set; }
    public static string STALLION                          { get; internal set; }
    public static string TOTAL                             { get; internal set; }
    public static string SELECT                            { get; internal set; }
    public static string GATE                              { get; internal set; }
    public static string RE_QUIRED_INSPECTION              { get; internal set; }
    public static string HAS_STARTED                       { get; internal set; }
    public static string DISTANCE                          { get; internal set; }
    public static string STARTLIST                         { get; internal set; }
    public static string INCLUDE_PAST                      { get; internal set; }
    public static string _DQ                               { get; internal set; }
    public static string IMPORT                            { get; internal set; }
}
