//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by xsd, Version=4.8.3928.0.
//
namespace EnduranceJudge.Application.Import.ImportFromFile.Models
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fei.org/Entry")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.fei.org/Entry", IsNullable=false)]
    public partial class HorseSport {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShowEntries", typeof(HorseSportShowEntries))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fei.org/Entry")]
    public partial class HorseSportShowEntries {

        private HorseSportShowEntriesShow[] showField;

        private HorseSportShowEntriesAthlete[] athleteField;

        private HorseSportShowEntriesHorse[] horseField;

        private HorseSportShowEntriesEvent[] eventField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Show")]
        public HorseSportShowEntriesShow[] Show {
            get {
                return this.showField;
            }
            set {
                this.showField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Athlete")]
        public HorseSportShowEntriesAthlete[] Athlete {
            get {
                return this.athleteField;
            }
            set {
                this.athleteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Horse")]
        public HorseSportShowEntriesHorse[] Horse {
            get {
                return this.horseField;
            }
            set {
                this.horseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Event")]
        public HorseSportShowEntriesEvent[] Event {
            get {
                return this.eventField;
            }
            set {
                this.eventField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fei.org/Entry")]
    public partial class HorseSportShowEntriesShow {

        private HorseSportShowEntriesShowVenue[] venueField;

        private string fEIIDField;

        private string typeCodeField;

        private string typeField;

        private string startDateField;

        private string endDateField;

        private string timeStampField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Venue")]
        public HorseSportShowEntriesShowVenue[] Venue {
            get {
                return this.venueField;
            }
            set {
                this.venueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FEIID {
            get {
                return this.fEIIDField;
            }
            set {
                this.fEIIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeCode {
            get {
                return this.typeCodeField;
            }
            set {
                this.typeCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fei.org/Entry")]
    public partial class HorseSportShowEntriesShowVenue {

        private string nameField;

        private string countryNOCField;

        private string countryField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CountryNOC {
            get {
                return this.countryNOCField;
            }
            set {
                this.countryNOCField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.fei.org/Entry")]
    public partial class HorseSportShowEntriesAthlete
    {
        private string fEIIDField;

        private string firstNameField;

        private string familyNameField;

        private string competingForField;

        private string birthDateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FEIID
        {
            get { return this.fEIIDField; }
            set { this.fEIIDField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FirstName
        {
            get { return this.firstNameField; }
            set { this.firstNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FamilyName
        {
            get { return this.familyNameField; }
            set { this.familyNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CompetingFor
        {
            get { return this.competingForField; }
            set { this.competingForField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BirthDate
        {
            get { return this.birthDateField; }
            set { this.birthDateField   = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fei.org/Entry")]
    public partial class HorseSportShowEntriesHorse {

        private string fEIIDField;

        private string nameField;

        private string stallionField;

        private string birthDayField;

        private string shortenNameField;

        private string studBookCodeField;

        private string studBookField;

        private string trainerFEIIDField;

        private string trainerFirstNameField;

        private string trainerFamilyNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FEIID {
            get {
                return this.fEIIDField;
            }
            set {
                this.fEIIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Stallion {
            get {
                return this.stallionField;
            }
            set {
                this.stallionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BirthDay {
            get {
                return this.birthDayField;
            }
            set {
                this.birthDayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ShortenName {
            get {
                return this.shortenNameField;
            }
            set {
                this.shortenNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StudBookCode {
            get {
                return this.studBookCodeField;
            }
            set {
                this.studBookCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StudBook {
            get {
                return this.studBookField;
            }
            set {
                this.studBookField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TrainerFEIID {
            get {
                return this.trainerFEIIDField;
            }
            set {
                this.trainerFEIIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TrainerFirstName {
            get {
                return this.trainerFirstNameField;
            }
            set {
                this.trainerFirstNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TrainerFamilyName {
            get {
                return this.trainerFamilyNameField;
            }
            set {
                this.trainerFamilyNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fei.org/Entry")]
    public partial class HorseSportShowEntriesEvent {

        private HorseSportShowEntriesEventAthleteEntry[] athleteEntryField;

        private string fEIIDField;

        private string disciplineCodeField;

        private string disciplineField;

        private string categoryCodeField;

        private string categoryField;

        private string codeField;

        private string levelCodeField;

        private string levelField;

        private string athletesMinAgeField;

        private string athletesMaxAgeField;

        private string horsesMinAgeField;

        private string horsesMaxAgeField;

        private string startDateField;

        private string endDateField;

        private string indoorField;

        private string officialTeamField;

        private string definiteEntriesDateField;

        private string startDateSubstAdditOCField;

        private string lastDateSubstitutionField;

        private string timeStampField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AthleteEntry")]
        public HorseSportShowEntriesEventAthleteEntry[] AthleteEntry {
            get {
                return this.athleteEntryField;
            }
            set {
                this.athleteEntryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FEIID {
            get {
                return this.fEIIDField;
            }
            set {
                this.fEIIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DisciplineCode {
            get {
                return this.disciplineCodeField;
            }
            set {
                this.disciplineCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Discipline {
            get {
                return this.disciplineField;
            }
            set {
                this.disciplineField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CategoryCode {
            get {
                return this.categoryCodeField;
            }
            set {
                this.categoryCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LevelCode {
            get {
                return this.levelCodeField;
            }
            set {
                this.levelCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AthletesMinAge {
            get {
                return this.athletesMinAgeField;
            }
            set {
                this.athletesMinAgeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AthletesMaxAge {
            get {
                return this.athletesMaxAgeField;
            }
            set {
                this.athletesMaxAgeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HorsesMinAge {
            get {
                return this.horsesMinAgeField;
            }
            set {
                this.horsesMinAgeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HorsesMaxAge {
            get {
                return this.horsesMaxAgeField;
            }
            set {
                this.horsesMaxAgeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Indoor {
            get {
                return this.indoorField;
            }
            set {
                this.indoorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OfficialTeam {
            get {
                return this.officialTeamField;
            }
            set {
                this.officialTeamField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DefiniteEntriesDate {
            get {
                return this.definiteEntriesDateField;
            }
            set {
                this.definiteEntriesDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StartDateSubstAdditOC {
            get {
                return this.startDateSubstAdditOCField;
            }
            set {
                this.startDateSubstAdditOCField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LastDateSubstitution {
            get {
                return this.lastDateSubstitutionField;
            }
            set {
                this.lastDateSubstitutionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fei.org/Entry")]
    public partial class HorseSportShowEntriesEventAthleteEntry {

        private HorseSportShowEntriesEventAthleteEntryHorseEntry[] horseEntryField;

        private string fEIIDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HorseEntry")]
        public HorseSportShowEntriesEventAthleteEntryHorseEntry[] HorseEntry {
            get {
                return this.horseEntryField;
            }
            set {
                this.horseEntryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FEIID {
            get {
                return this.fEIIDField;
            }
            set {
                this.fEIIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fei.org/Entry")]
    public partial class HorseSportShowEntriesEventAthleteEntryHorseEntry {

        private string fEIIDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FEIID {
            get {
                return this.fEIIDField;
            }
            set {
                this.fEIIDField = value;
            }
        }
    }
}
